web:
  host: "127.0.0.1"
  port: "8080"
  tls: false
  cert_private_path: ""
  cert_public_path: ""

database:
  type: "mysql" # mysql or sqlite
  path: ""      # sqlite path
  host: ""      # mysql host 
  port: ""
  name: ""
  user: ""
  pass: ""

user:
  cookie_timeout: 604800
  pass_hash_type: "md5" #密码哈希类型 text md5 
  avatar_save_path: "/data/avatar/" #头像保存的真实位置
  avatar_ginrouter_path: "/avatar/" #gin 路由的路径
  avatar_path: "/static/avatars/def.png"

file:
  max_size: 52428800
  pahts:
    avatar: "./data/avatar/"
    image:  "./data/upload/image/"
    video:  "./data/upload/video/"
    music:  "./data/upload/music/"
    pdf:    "./data/upload/pdf/"
    other:  "./data/upload/other/"

  allow_image_mime:
    image/jpeg: true
    image/png: true
    image/gif: true
    image/bmp: true

  allow_video_mime:
    video/mp4: true
    video/x-msvideo: true
    video/quicktime: true
    video/x-flv: true
    video/mpeg: true

  allow_music_mime:
    audio/mpeg: true
    audio/aac: true
    audio/wav: true
    audio/flac: true

  allow_pdf_mime:
    application/pdf: true




warehouses:
  repos_per_page: 12      #每页显示多少个仓库
  repo_items_per_page: 10 #每个仓库的每页显示多少个物品


configed: false
